backend:
  name: github
  repo: mohammad ghanbari/personal-site-nahaei# این بخش را طبق راهنمای زیر تغییر بده
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "poems"
    label: "شعرها"
    folder: "src/content/poems"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "عنوان", name: "title", widget: "string" }
      - { label: "تاریخ انتشار", name: "date", widget: "datetime" }
      - { label: "متن شعر", name: "body", widget: "markdown" }